name: Deploy App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/setup-node@v1
    - name: Configure SSH
      run: |
          git config --global user.email "mohammedismayil10@gmail.com"
          git config --global user.name "mohammedismayil"
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName "${{ secrets.SSH_HOST }}"
            User "${{ secrets.SSH_USER }}"
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
    - name: Starting the Docker compose
      run: |
         ssh staging 'git pull https://github.com/mohammedismayil/docker-compose-sample.git'
         ssh staging 'echo okkok'
    
    
# ssh staging 'rm -rfv reactMERN'
#  ssh staging 'docker-compose down'